site: Bokeh Front Page
url: https://bokeh.org

ga_id: "UA-127553611-4"

collections:
  - features
  - goals
  - scenarios
  - users

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap

exclude:
  - README.md
  - Makefile
